[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[functions]
directory = "netlify/functions"

# SPA redirect - catch all routes and redirect to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
